<a href="https://colab.research.google.com/github/BYEONGSEOKKIM/algorithm/blob/master/pythonbase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1+1

2

In [2]:
2*-3

-6

In [3]:
4/3

1.3333333333333333

In [4]:
4//3

1

In [5]:
4%3

1

In [6]:
3**2

9

In [7]:
2<3

True

In [8]:
a=2

In [9]:
a

2

In [10]:
a=a+3
a

5

In [11]:
a /= 2
a 

2.5

In [12]:
a='test'

In [13]:
b=3

In [16]:
f'{a} is {b}'

'test is 3'

In [17]:
c= 100/7
c

14.285714285714286

In [19]:
f'{c:.2f}'

'14.29'

In [21]:
[2,3,'r']

[2, 3, 'r']

In [22]:
[[1,2,3,],[4,6,7]]

[[1, 2, 3], [4, 6, 7]]

In [25]:
a = [1,2,3]
b=[4,5,6]

In [26]:
a+b

[1, 2, 3, 4, 5, 6]

In [29]:
a.append(3)
a

[1, 2, 3, 3, 3, 3]

In [30]:
b[:3]

[4, 5, 6]

In [31]:
b[1:3]

[5, 6]

In [32]:
d = {'python':2, '통계':3}
d

{'python': 2, '통계': 3}

In [33]:
d['python']

2

In [34]:
d.keys()

dict_keys(['python', '통계'])

In [36]:
d.values()

dict_values([2, 3])

In [38]:
x = 2
if x<3:
  print(f'{x}는 3보다 작다')
else:
  print(f'{x}는 3보다 크다')

2는 3보다 작다


In [39]:
for i in range(5):
  print(i)


0
1
2
3
4


In [40]:
a = []
for i in range(5):
  a.append(2*i)

a

[0, 2, 4, 6, 8]

In [41]:
[2*i for i in range(5)]

[0, 2, 4, 6, 8]

In [43]:
[i for  i in range(10) if i%2==0]

[0, 2, 4, 6, 8]

In [44]:
[i if i%2==0 else 1 for i in range(10)]

[0, 1, 2, 1, 4, 1, 6, 1, 8, 1]

In [45]:
def test (a,b):
  return a+b

In [46]:
test(2,3)

5

In [48]:
# numpy

In [49]:
import numpy as np

In [50]:
arr=np.array([1,2,3,4,5])

In [51]:
arr.shape

(5,)

In [52]:
arr + 2

array([3, 4, 5, 6, 7])

In [53]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [54]:
arr[:2]

array([1, 2])

In [55]:
arr[3:5]

array([4, 5])

In [57]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [58]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [59]:
np.linspace(0,3,11)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. ])

In [60]:
arr2 = np.array([[1,3],[5,7]])
arr2

array([[1, 3],
       [5, 7]])

In [61]:
arr2.shape

(2, 2)

In [62]:
np.save('test.npy',arr2)

In [63]:
np.load('test.npy')

array([[1, 3],
       [5, 7]])

In [66]:
# pandas

In [65]:
import pandas as pd

In [67]:
df =pd.read_csv('sport_test.csv')
df

학생번호  학년    악력  윗몸일으키기  점수  순위
0     1   1  40.2      34  15   4
1     2   1  34.2      14   7  10
2     3   1  28.8      27  11   7
3     4   2  39.0      27  14   5
4     5   2  50.9      32  17   2
5     6   2  36.5      20   9   9
6     7   3  36.6      31  13   6
7     8   3  49.2      37  18   1
8     9   3  26.0      28  10   8
9    10   3  47.4      32  16   3

In [68]:
df.head(3)

학생번호  학년    악력  윗몸일으키기  점수  순위
0     1   1  40.2      34  15   4
1     2   1  34.2      14   7  10
2     3   1  28.8      27  11   7

In [69]:
df.head()

학생번호  학년    악력  윗몸일으키기  점수  순위
0     1   1  40.2      34  15   4
1     2   1  34.2      14   7  10
2     3   1  28.8      27  11   7
3     4   2  39.0      27  14   5
4     5   2  50.9      32  17   2

In [70]:
df.tail()

학생번호  학년    악력  윗몸일으키기  점수  순위
5     6   2  36.5      20   9   9
6     7   3  36.6      31  13   6
7     8   3  49.2      37  18   1
8     9   3  26.0      28  10   8
9    10   3  47.4      32  16   3

In [71]:
df[2:5]

학생번호  학년    악력  윗몸일으키기  점수  순위
2     3   1  28.8      27  11   7
3     4   2  39.0      27  14   5
4     5   2  50.9      32  17   2

In [72]:
df['악력']

0    40.2
1    34.2
2    28.8
3    39.0
4    50.9
5    36.5
6    36.6
7    49.2
8    26.0
9    47.4
Name: 악력, dtype: float64

In [74]:
df[['학년','점수']]

학년  점수
0   1  15
1   1   7
2   1  11
3   2  14
4   2  17
5   2   9
6   3  13
7   3  18
8   3  10
9   3  16

In [75]:
df.loc[1,'학년']

1

In [76]:
df.loc[1:3, '악력']

1    34.2
2    28.8
3    39.0
Name: 악력, dtype: float64

In [77]:
df[df['악력']<30]

학생번호  학년    악력  윗몸일으키기  점수  순위
2     3   1  28.8      27  11   7
8     9   3  26.0      28  10   8

In [78]:
df.shape

(10, 6)

In [79]:
df.columns

Index(['학생번호', '학년', '악력', '윗몸일으키기', '점수', '순위'], dtype='object')

In [80]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [81]:
df.describe()

학생번호         학년         악력     윗몸일으키기         점수        순위
count  10.00000  10.000000  10.000000  10.000000  10.000000  10.00000
mean    5.50000   2.100000  38.880000  28.200000  13.000000   5.50000
std     3.02765   0.875595   8.337306   6.828047   3.651484   3.02765
min     1.00000   1.000000  26.000000  14.000000   7.000000   1.00000
25%     3.25000   1.250000  34.775000  27.000000  10.250000   3.25000
50%     5.50000   2.000000  37.800000  29.500000  13.500000   5.50000
75%     7.75000   3.000000  45.600000  32.000000  15.750000   7.75000
max    10.00000   3.000000  50.900000  37.000000  18.000000  10.00000